/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package riskassesment;

import java.io.File;
import java.util.ArrayList;
import org.jsoup.Jsoup;
import org.jsoup.nodes.Document;
import org.jsoup.nodes.Element;
import org.jsoup.select.Elements;

/**
 *
 * @author Elcot
 */
public class FirstPhase extends javax.swing.JFrame {

    /**
     * Creates new form FirstPhase
     */
    
    public static ArrayList cluster1=new ArrayList();
    public static ArrayList cluster2=new ArrayList();
    public static ArrayList cluster3=new ArrayList();
    public static ArrayList cluster4=new ArrayList();
    
    public FirstPhase() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(102, 0, 102));

        jLabel1.setFont(new java.awt.Font("French Script MT", 1, 48)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("First Phase");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(376, 376, 376)
                .addComponent(jLabel1)
                .addContainerGap(388, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(41, 41, 41))
        );

        jButton1.setText("GIP = Group Identification Phase");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        jButton2.setText("Second Phase");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 899, Short.MAX_VALUE)
                    .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 319, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(22, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        
        SecondPhase cf=new SecondPhase();
        cf.setTitle("Second Phase");
        cf.setVisible(true);
        cf.setResizable(false);
        
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        
        ArrayList FileNames=MainFrame.FileNames;                
        
        for(int i=0;i<FileNames.size();i++)
        {
            String fn=FileNames.get(i).toString().trim();
            System.out.println(fn.trim());
            try 
            {
                File input = new File(fn.trim());
                Document doc = Jsoup.parse(input, "UTF-8");		
                
                Elements links = doc.select("post");                
                for (Element link : links) 
                {
                    String postid=link.attr("id");
                    System.out.println("postid: "+postid.trim()); 
                    
                    doc = Jsoup.parse(link.toString());
                     
                    String userid="",username="",sex="",age="",city="",province="",country="",date="",body="";
                    try
                    {
                        Elements linksk1 = doc.select("user");
                        for (Element link2 : linksk1) 
                        {
                            userid=link2.attr("id");
                            System.out.println("userid: "+userid);                                                                                    
                            break;
                        }                                                                        
                    }
                    catch(Exception e)
                    {
                        e.printStackTrace();
                    }
                    
                    try
                    {
                        Elements linksk1 = doc.select("username");
                        username=linksk1.get(0).text();
                        System.out.println("username: "+username);                                                                                               
                    }
                    catch(Exception e)
                    {
                        e.printStackTrace();
                    }
                    try
                    {
                        Elements linksk1 = doc.select("sex");
                        sex=linksk1.get(0).text();
                        System.out.println("sex: "+sex);                                                                                               
                    }
                    catch(Exception e)
                    {
                        e.printStackTrace();
                    }
                    try
                    {
                        Elements linksk1 = doc.select("age");
                        age=linksk1.get(0).text();
                        System.out.println("age: "+age);                                                                                               
                    }
                    catch(Exception e)
                    {
                        e.printStackTrace();
                    }
                    try
                    {
                        Elements linksk1 = doc.select("city");
                        city=linksk1.get(0).text();
                        System.out.println("city: "+city);                                                                                               
                    }
                    catch(Exception e)
                    {
                        e.printStackTrace();
                    }
                    try
                    {
                        Elements linksk1 = doc.select("province");
                        province=linksk1.get(0).text();
                        System.out.println("province: "+province);                                                                                               
                    }
                    catch(Exception e)
                    {
                        e.printStackTrace();
                    }
                    try
                    {
                        Elements linksk1 = doc.select("country");
                        country=linksk1.get(0).text();
                        System.out.println("country: "+country);                                                                                               
                    }
                    catch(Exception e)
                    {
                        e.printStackTrace();
                    }
                    try
                    {
                        Elements linksk1 = doc.select("date");
                        date=linksk1.get(0).text();
                        System.out.println("date: "+date);                                                                                               
                    }
                    catch(Exception e)
                    {
                        e.printStackTrace();
                    }
                    try
                    {                        
                        Elements linksk1 = doc.select("body");
                        body=linksk1.get(0).text();
                        System.out.println("body: "+body);                                                                                               
                    }
                    catch(Exception e)
                    {
                        e.printStackTrace();
                    }
                    System.out.println("==========================================");
                    if(sex.trim().equals("M"))
                    {
                        cluster1.add(postid+","+userid+","+username+","+sex+","+age+","+city+","+province+","+country+","+date+"-->"+body);
                    }
                    else        // Female
                    {
                        cluster2.add(postid+","+userid+","+username+","+sex+","+age+","+city+","+province+","+country+","+date+"-->"+body);
                    }
                    
                    if(Integer.parseInt(age)<=18)
                    {
                        cluster3.add(postid+","+userid+","+username+","+sex+","+age+","+city+","+province+","+country+","+date+"-->"+body);
                    }
                    else
                    {
                        cluster4.add(postid+","+userid+","+username+","+sex+","+age+","+city+","+province+","+country+","+date+"-->"+body);
                    }
                }
            }
            catch(Exception e)
            {
                e.printStackTrace();
            }            
        }
        
        jTextArea1.setText("");
        
        jTextArea1.append("============================================================================================================\n");
        jTextArea1.append("                                               Group - 1 (Male)\n");
        jTextArea1.append("============================================================================================================\n");
        for(int i=0;i<cluster1.size();i++)
        {
            String s=cluster1.get(i).toString().trim().replaceAll("-->", ",");
            jTextArea1.append(s.trim()+"\n");
        }
        jTextArea1.append("\n");
        
        jTextArea1.append("============================================================================================================\n");
        jTextArea1.append("                                               Group - 2 (Female)\n");
        jTextArea1.append("============================================================================================================\n");
        for(int i=0;i<cluster2.size();i++)
        {
            String s=cluster2.get(i).toString().trim().replaceAll("-->", ",");
            jTextArea1.append(s.trim()+"\n");
        }
        jTextArea1.append("\n");
        
        jTextArea1.append("============================================================================================================\n");
        jTextArea1.append("                                               Group - 3 (<=18)\n");
        jTextArea1.append("============================================================================================================\n");
        for(int i=0;i<cluster3.size();i++)
        {
            String s=cluster3.get(i).toString().trim().replaceAll("-->", ",");
            jTextArea1.append(s.trim()+"\n");
        }
        jTextArea1.append("\n");
        
        jTextArea1.append("============================================================================================================\n");
        jTextArea1.append("                                              Group - 4 (>18)\n");
        jTextArea1.append("============================================================================================================\n");
        for(int i=0;i<cluster4.size();i++)
        {
            String s=cluster4.get(i).toString().trim().replaceAll("-->", ",");
            jTextArea1.append(s.trim()+"\n");
        }
        jTextArea1.append("\n");
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FirstPhase.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FirstPhase.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FirstPhase.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FirstPhase.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FirstPhase().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    // End of variables declaration//GEN-END:variables
}
