/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package riskassesment;

import java.io.File;
import java.io.FileInputStream;
import java.util.ArrayList;

/**
 *
 * @author Elcot
 */
public class SecondPhase extends javax.swing.JFrame {

    /**
     * Creates new form SecondPhase
     */
    
    public static ArrayList Content=new ArrayList();
    public static ArrayList Result=new ArrayList();
    public static ArrayList cyberbullyingWords=new ArrayList();
    
    public SecondPhase() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(102, 0, 153));

        jLabel1.setFont(new java.awt.Font("French Script MT", 1, 48)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Second Phase");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(370, 370, 370)
                .addComponent(jLabel1)
                .addContainerGap(364, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1))
        );

        jButton1.setText("RAP = Risk Assesment Phase");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        jButton2.setText("Generate Training and Testing Datasets");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, 885, Short.MAX_VALUE)
                    .addComponent(jScrollPane1)
                    .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 334, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 19, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        
        String cw="";
        try
        {
            String fname="Cyberbullying Words.txt";
            File fe = new File(fname);
            FileInputStream fis=new FileInputStream(fe);
            byte data[]=new byte[fis.available()];
            fis.read(data);
            fis.close();
            cw=new String(data);            
        }
        catch(Exception e)
        {
            e.printStackTrace();
        }
        String cyberbull[]=cw.trim().split("\n");        
        for(int i=0;i<cyberbull.length;i++)
        {
            String word=cyberbull[i].trim();
            if(!(cyberbullyingWords.contains(word.trim())))
            {
                cyberbullyingWords.add(word.trim());
            }
        }
        
        jTextArea1.setText("");
        
        ArrayList cluster1=FirstPhase.cluster1;
        ArrayList cluster2=FirstPhase.cluster2;
        ArrayList cluster3=FirstPhase.cluster3;
        ArrayList cluster4=FirstPhase.cluster4;
        
        jTextArea1.append("============================================================================================================\n");
        jTextArea1.append("                                               Group - 1 (Male)\n");
        jTextArea1.append("============================================================================================================\n");        
        for(int i=0;i<cluster1.size();i++)
        {
            String record=cluster1.get(i).toString().trim();
            
            String status="Normal Behavior";
            String s[]=record.trim().split("-->");            
            String posts=s[s.length-1].toLowerCase().trim().replaceAll("[^\\w\\s]", "");
            String sp[]=posts.trim().split(" ");
            for(int j=0;j<sp.length;j++)
            {
                if((cyberbullyingWords.contains(sp[j].trim())))
                {
                    status="Risky";
                    break;
                }
            }            
            jTextArea1.append(record.trim().replaceAll("-->", ",")+"-->"+status+"\n");
            Content.add(record.trim().replaceAll("-->", ","));
            Result.add(status.trim());
        }
        jTextArea1.append("\n");
        
        jTextArea1.append("============================================================================================================\n");
        jTextArea1.append("                                               Group - 2 (Female)\n");
        jTextArea1.append("============================================================================================================\n");        
        for(int i=0;i<cluster2.size();i++)
        {
            String record=cluster2.get(i).toString().trim();
            
            String status="Normal Behavior";
            String s[]=record.trim().split("-->");            
            String posts=s[s.length-1].toLowerCase().trim().replaceAll("[^\\w\\s]", "");
            String sp[]=posts.trim().split(" ");
            for(int j=0;j<sp.length;j++)
            {
                if((cyberbullyingWords.contains(sp[j].trim())))
                {
                    status="Risky";
                    break;
                }
            }            
            jTextArea1.append(record.trim().replaceAll("-->", ",")+"-->"+status+"\n");
            Content.add(record.trim().replaceAll("-->", ","));
            Result.add(status.trim());
        }
        jTextArea1.append("\n");
        
        jTextArea1.append("============================================================================================================\n");
        jTextArea1.append("                                               Group - 3 (<=18)\n");
        jTextArea1.append("============================================================================================================\n");        
        for(int i=0;i<cluster3.size();i++)
        {
            String record=cluster3.get(i).toString().trim();
            
            String status="Normal Behavior";
            String s[]=record.trim().split("-->");            
            String posts=s[s.length-1].toLowerCase().trim().replaceAll("[^\\w\\s]", "");
            String sp[]=posts.trim().split(" ");
            for(int j=0;j<sp.length;j++)
            {
                if((cyberbullyingWords.contains(sp[j].trim())))
                {
                    status="Risky";
                    break;
                }
            }            
            jTextArea1.append(record.trim().replaceAll("-->", ",")+"-->"+status+"\n");
            Content.add(record.trim().replaceAll("-->", ","));
            Result.add(status.trim());
        }
        jTextArea1.append("\n");
        
        jTextArea1.append("============================================================================================================\n");
        jTextArea1.append("                                               Group - 4 (>18)\n");
        jTextArea1.append("============================================================================================================\n");        
        for(int i=0;i<cluster4.size();i++)
        {
            String record=cluster4.get(i).toString().trim();
            
            String status="Normal Behavior";
            String s[]=record.trim().split("-->");            
            String posts=s[s.length-1].toLowerCase().trim().replaceAll("[^\\w\\s]", "");
            String sp[]=posts.trim().split(" ");
            for(int j=0;j<sp.length;j++)
            {
                if((cyberbullyingWords.contains(sp[j].trim())))
                {
                    status="Risky";
                    break;
                }
            }            
            jTextArea1.append(record.trim().replaceAll("-->", ",")+"-->"+status+"\n");
            Content.add(record.trim().replaceAll("-->", ","));
            Result.add(status.trim());
        }
        jTextArea1.append("\n");
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        
        TrainingTesting TT=new TrainingTesting();
        TT.setTitle("Generate Training and Testing Dataset");
        TT.setVisible(true);
        TT.setResizable(false);	
        
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SecondPhase.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SecondPhase.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SecondPhase.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SecondPhase.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SecondPhase().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    // End of variables declaration//GEN-END:variables
}
